#!/bin/bash -e

ROOTDIR=`readlink -f root`

rm -rf --one-file-system $ROOTDIR

mkdir -p $ROOTDIR/etc/apt/trusted.gpg.d/
gpg --export 82B129927FA3303E > root/etc/apt/trusted.gpg.d/raspberrypi-archive-keyring.gpg
gpg --export 9165938D90FDDD2E > root/etc/apt/trusted.gpg.d/raspbian-archive-keyring.gpg

http_proxy=$APT_HTTP_PROXY /usr/sbin/multistrap -d $ROOTDIR -f multistrap.conf

export QEMU_LD_PREFIX=$(readlink -f $ROOTDIR)

# If you want to use fakeroot/fakechroot for some reason,
# you will need to install them in multistrap.conf.
#MYCHROOT="fakechroot fakeroot chroot"
MYCHROOT="proot -0 -q qemu-arm -w / -r"

echo "Running preinst scripts..."

for script in $ROOTDIR/var/lib/dpkg/info/*.preinst; do
        [ "$script" = "$ROOTDIR/var/lib/dpkg/info/vpnc.preinst" ] && continue
        echo "I: run preinst script ${script##$ROOTDIR}"
        DPKG_MAINTSCRIPT_NAME=preinst \
        DPKG_MAINTSCRIPT_PACKAGE="`basename $script .preinst`" \
        $MYCHROOT $ROOTDIR ${script##$ROOTDIR} install
done

echo "Running dpkg --configure -a"

# don't run makedev
# we will create device nodes later, after we are done with the system dev
rm -f $ROOTDIR/var/lib/dpkg/info/makedev.postinst

# work around https://pad.lv/1727874
rm -f $ROOTDIR/var/lib/dpkg/info/raspbian-archive-keyring.postinst
ln -sf /usr/share/keyrings/raspbian-archive-keyring.gpg $ROOTDIR/etc/apt/trusted.gpg.d/

# work around PAM error
ln -s -f /bin/true $ROOTDIR/usr/bin/chfn

if [ ! -c "$ROOTDIR/dev/urandom" ]; then
	echo "Mounting /dev/urandom"
	touch $ROOTDIR/dev/urandom
	sudo mount -o bind /dev/urandom $ROOTDIR/dev/urandom
fi

DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true \
 LC_ALL=C LANGUAGE=C LANG=C $MYCHROOT $ROOTDIR /usr/bin/dpkg --configure -a || true

if [ -c "$ROOTDIR/dev/urandom" ]; then
	echo "Unmounting /dev/urandom"
	sudo umount $ROOTDIR/dev/urandom
	rm -f $ROOTDIR/dev/urandom
fi

#echo "Busybox linking..."

#$MYCHROOT $ROOTDIR busybox --install -s

echo "Preparing root..."

# no root password
$MYCHROOT $ROOTDIR passwd -d root

# initialize /etc/fstab
echo proc /proc proc defaults 0 0 > $ROOTDIR/etc/fstab

# hostname
echo $HOSTNAME > $ROOTDIR/etc/hostname

# The following profile fragment makes the terminal rows/cols
# be correct when logging in over serial
cat <<EOF > $ROOTDIR/etc/profile.d/resize.sh
resize() {

  old=\$(stty -g)
  stty raw -echo min 0 time 5

  printf '\033[18t' > /dev/tty
  IFS=';t' read -r _ rows cols _ < /dev/tty

  stty "\$old"

  # echo "cols:\$cols"
  # echo "rows:\$rows"
  stty cols "\$cols" rows "\$rows"
}

[ \$(tty) = /dev/ttyAMA0 ] && resize
EOF

echo "Installing modules..."

tar -xf ../kernel/kernel-root.tar.gz -C $ROOTDIR

echo "Installing opt packages..."

for PACKAGE in $PACKAGES
 do echo installing $PACKAGE ...
    make -C ../packages/$PACKAGE DESTDIR="$ROOTDIR" MYCHROOT="$MYCHROOT" install
done

$ROOTDIR/sbin/ldconfig -r $ROOTDIR

echo "Keybow install..."

# cp keybow $ROOTDIR/usr/bin/keybow
# chmod a+x $ROOTDIR/usr/bin/keybow

cp keybow.service $ROOTDIR/etc/systemd/system/keybow.service

$MYCHROOT $ROOTDIR systemctl reenable keybow.service


echo "Cleaning up..."

$MYCHROOT $ROOTDIR dpkg --force-all --purge perl-base debconf libdb5.3
$MYCHROOT $ROOTDIR dpkg --force-all --purge dpkg

./cleanup $ROOTDIR excludes.conf > /dev/null
mkdir -p $ROOTDIR/etc/dpkg/dpkg.cfg.d
cp excludes.conf $ROOTDIR/etc/dpkg/dpkg.cfg.d/

# MINIMAL

echo "Misc housekeeping..."

#ln -sf /sbin/init $ROOTDIR/init
cp init $ROOTDIR/init
chmod a+x $ROOTDIR/init

ln -sf /proc/mounts $ROOTDIR/etc/mtab

echo "Creating minimal device nodes..."

# this must be done last. if the fakeroot devices exist on the system,
# fakechroot wont be able to read from them, which breaks systemd setup.
cd $ROOTDIR/dev
fakeroot /sbin/MAKEDEV std
cd ../..

echo "Packing rootfs..."

$MYCHROOT $ROOTDIR sh -c "cd / && find * -xdev -not \( \
              -path host-rootfs -prune \
              -path run -prune \
              -path proc -prune \
              -path sys -prune \
              -path boot -prune \
           \) | cpio --create -H newc" | xz -C crc32 -9 > initrd
